// Trade status options
export const TRADE_STATUS = {
    OPEN: 'open',
    CLOSED: 'closed'
};

// Asset types
export const ASSET_TYPES = {
    STOCK: 'Stock',
    ETF: 'ETF',
    OPTION: 'Option'
};

// Trade directions
export const DIRECTIONS = {
    LONG: 'LONG',
    SHORT: 'SHORT'
};

// Strategies
export const STRATEGIES = {
    EP: 'EP',
    MB: 'MB',
    PBB: 'PBB',
    MOMENTUM: 'MOMENTUM'
};

// Setups
export const SETUPS = [
    'EP',
    'VCP',
    'Inside Day',
    'Inside Week',
    'HTF',
    'Flat Base',
    'Bull Flag',
    'PB',
    'IPO Base',
    'Triangle',
    'Falling Wedge'
];

// Trade model schema
export const TradeSchema = {
    id: 'string', // UUID, hidden from UI but used internally
    ticker: 'string',
    asset_type: Object.values(ASSET_TYPES),
    direction: Object.values(DIRECTIONS),
    status: Object.values(TRADE_STATUS),
    entry_date: 'date',
    avg_cost: 'decimal',
    total_shares: 'integer',
    shares_remaining: 'decimal',
    total_cost: 'decimal',
    market_value: 'decimal',
    weight_percentage: 'decimal',
    trimmed_percentage: 'decimal',
    strategy: Object.values(STRATEGIES),
    setups: [SETUPS], // Array of setups
    initial_stop_loss: 'decimal',
    stop_loss_33: 'decimal',
    stop_loss_66: 'decimal',
    stop_loss_100: 'decimal',
    unrealized_pnl_percentage: 'decimal',
    unrealized_pnl: 'decimal',
    realized_pnl_percentage: 'decimal',
    realized_pnl: 'decimal',
    risk_reward_ratio: 'decimal',
    open_risk: 'decimal',
    portfolio_impact: 'decimal',
    mae: 'decimal', // Maximum Adverse Excursion
    mfe: 'decimal',  // Maximum Favorable Excursion
    last_price: 'decimal'
};

// Sample trades for development
export const SAMPLE_TRADES = [
    {
        id: '1',
        ticker: 'AAPL',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.OPEN,
        entry_date: '2023-12-06',
        avg_cost: 150.00,
        total_shares: 100,
        shares_remaining: 100,
        total_cost: 15000,
        market_value: 15000,
        trimmed: 25,
        weight: 5,
        strategy: STRATEGIES.MOMENTUM,
        setups: ['VCP', 'Bull Flag'],
        initial_sl: 145.00,
        sl_33: 146.00,
        sl_66: 147.50,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 0,
        realized_pnl: 0,
        rrr: 3.5,
        open_risk: 2.5,
        portfolio_impact: 2.5,
        mae: -2.1,
        mfe: 4.2,
        last_price: null
    },
    {
        id: '2',
        ticker: 'NVDA',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.OPEN,
        entry_date: '2023-12-05',
        avg_cost: 465.00,
        total_shares: 50,
        shares_remaining: 50,
        total_cost: 23250,
        market_value: 23250,
        trimmed: 30,
        weight: 8,
        strategy: STRATEGIES.EP,
        setups: ['EP', 'HTF'],
        initial_sl: 450.00,
        sl_33: 455.00,
        sl_66: 460.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 0,
        realized_pnl: 0,
        rrr: 3.2,
        open_risk: 3.0,
        portfolio_impact: 3.8,
        mae: -1.5,
        mfe: 3.1,
        last_price: null
    },
    {
        id: '3',
        ticker: 'META',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.CLOSED,
        entry_date: '2023-12-01',
        avg_cost: 320.00,
        total_shares: 80,
        shares_remaining: 0,
        total_cost: 25600,
        market_value: 0,
        trimmed: 100,
        weight: 0,
        strategy: STRATEGIES.MB,
        setups: ['Inside Week'],
        initial_sl: 310.00,
        sl_33: 313.00,
        sl_66: 316.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 5.2,
        realized_pnl: 1331.20,
        rrr: 2.8,
        open_risk: 0,
        portfolio_impact: 0,
        mae: -1.2,
        mfe: 5.8,
        last_price: null
    },
    {
        id: '4',
        ticker: 'AMD',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.OPEN,
        entry_date: '2023-12-04',
        avg_cost: 120.00,
        total_shares: 150,
        shares_remaining: 150,
        total_cost: 18000,
        market_value: 18000,
        trimmed: 0,
        weight: 6,
        strategy: STRATEGIES.PBB,
        setups: ['PB'],
        initial_sl: 115.00,
        sl_33: 116.50,
        sl_66: 118.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 0,
        realized_pnl: 0,
        rrr: 3.0,
        open_risk: 2.8,
        portfolio_impact: 2.2,
        mae: -1.8,
        mfe: 2.5,
        last_price: null
    },
    {
        id: '5',
        ticker: 'MSFT',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.CLOSED,
        entry_date: '2023-11-28',
        avg_cost: 370.00,
        total_shares: 60,
        shares_remaining: 0,
        total_cost: 22200,
        market_value: 0,
        trimmed: 100,
        weight: 0,
        strategy: STRATEGIES.EP,
        setups: ['EP', 'Triangle'],
        initial_sl: 360.00,
        sl_33: 363.00,
        sl_66: 366.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 4.1,
        realized_pnl: 910.20,
        rrr: 2.5,
        open_risk: 0,
        portfolio_impact: 0,
        mae: -1.5,
        mfe: 4.5,
        last_price: null
    },
    {
        id: '6',
        ticker: 'GOOGL',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.OPEN,
        entry_date: '2023-12-07',
        avg_cost: 135.00,
        total_shares: 200,
        shares_remaining: 200,
        total_cost: 27000,
        market_value: 27000,
        trimmed: 0,
        weight: 7,
        strategy: STRATEGIES.MB,
        setups: ['Inside Day'],
        initial_sl: 130.00,
        sl_33: 131.50,
        sl_66: 133.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 0,
        realized_pnl: 0,
        rrr: 3.2,
        open_risk: 2.2,
        portfolio_impact: 3.1,
        mae: -1.2,
        mfe: 1.8,
        last_price: null
    },
    {
        id: '7',
        ticker: 'TSLA',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.SHORT,
        status: TRADE_STATUS.CLOSED,
        entry_date: '2023-11-30',
        avg_cost: 240.00,
        total_shares: 100,
        shares_remaining: 0,
        total_cost: 24000,
        market_value: 0,
        trimmed: 100,
        weight: 0,
        strategy: STRATEGIES.MB,
        setups: ['Falling Wedge'],
        initial_sl: 245.00,
        sl_33: 243.50,
        sl_66: 242.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 3.8,
        realized_pnl: 912,
        rrr: 2.8,
        open_risk: 0,
        portfolio_impact: 0,
        mae: -1.8,
        mfe: 4.2,
        last_price: null
    },
    {
        id: '8',
        ticker: 'AMZN',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.OPEN,
        entry_date: '2023-12-05',
        avg_cost: 145.00,
        total_shares: 175,
        shares_remaining: 175,
        total_cost: 25375,
        market_value: 25375,
        trimmed: 15,
        weight: 6.5,
        strategy: STRATEGIES.PBB,
        setups: ['Bull Flag'],
        initial_sl: 140.00,
        sl_33: 141.50,
        sl_66: 143.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 0,
        realized_pnl: 0,
        rrr: 3.0,
        open_risk: 2.5,
        portfolio_impact: 2.8,
        mae: -1.5,
        mfe: 2.2,
        last_price: null
    },
    {
        id: '9',
        ticker: 'CRM',
        asset_type: ASSET_TYPES.STOCK,
        direction: DIRECTIONS.LONG,
        status: TRADE_STATUS.CLOSED,
        entry_date: '2023-11-29',
        avg_cost: 250.00,
        total_shares: 90,
        shares_remaining: 0,
        total_cost: 22500,
        market_value: 0,
        trimmed: 100,
        weight: 0,
        strategy: STRATEGIES.EP,
        setups: ['EP', 'VCP'],
        initial_sl: 245.00,
        sl_33: 246.50,
        sl_66: 248.00,
        unrealized_pnl_percentage: 0,
        unrealized_pnl: 0,
        realized_pnl_percentage: 4.5,
        realized_pnl: 1012.50,
        rrr: 2.5,
        open_risk: 0,
        portfolio_impact: 0,
        mae: -1.2,
        mfe: 4.8,
        last_price: null
    }
];
